import { useEffect, useState, type FormEvent } from 'react';
import { ConfirmDialog } from '../../../components/base/ConfirmDialog';
import { createAdminAssetAdjustment, fetchAdminAirdropAssetOptions, fetchAdminAssetAdjustmentReversalSource, type AdminAirdropAssetOption, type AdminAssetAdjustmentRequest, type AdminReversalSource, type AssetAdjustmentType } from '../../api/adminAssetsApi';

const positive = (value: string) => /^(?=.*[1-9])\d+(?:\.\d+)?$/.test(value);

/**
 * Airdrop 與 accounting correction 分開呈現。所有金額保留 decimal string；reversal 的帳戶與方向只接受 lookup 結果。
 */
export function AssetAdjustmentForm() {
  const [type, setType] = useState<AssetAdjustmentType>('MANUAL_CORRECTION'); const [assets, setAssets] = useState<AdminAirdropAssetOption[]>([]);
  const [form, setForm] = useState<AdminAssetAdjustmentRequest>({ adjustmentType: 'MANUAL_CORRECTION', userId: '', accountType: 'SPOT', assetSymbol: '', direction: 'CREDIT', amount: '', reason: '' });
  const [sourceId, setSourceId] = useState(''); const [source, setSource] = useState<AdminReversalSource | null>(null); const [error, setError] = useState<string | null>(null); const [confirming,setConfirming]=useState(false); const [submitting,setSubmitting]=useState(false); const [result,setResult]=useState<string | null>(null);
  useEffect(() => { void fetchAdminAirdropAssetOptions().then((next) => { setAssets(next); setForm((v) => ({ ...v, assetSymbol: v.assetSymbol || next[0]?.assetSymbol || '' })); }).catch(() => setError('無法載入可調整資產。')); }, []);
  function change<K extends keyof AdminAssetAdjustmentRequest>(key: K, value: AdminAssetAdjustmentRequest[K]) { setForm((v) => ({ ...v, [key]: value })); }
  function choose(next: AssetAdjustmentType) { setType(next); setSource(null); setSourceId(''); setError(null); setForm({ adjustmentType: next, userId: '', accountType: 'SPOT', assetSymbol: assets[0]?.assetSymbol ?? '', direction: 'CREDIT', amount: '', reason: '', sourceBusinessType: '', sourceBusinessId: '', incidentReference: '' }); }
  async function lookup() { if (!sourceId.trim()) { setError('請輸入來源 Ledger Entry ID。'); return; } setError(null); try { const next=await fetchAdminAssetAdjustmentReversalSource(sourceId.trim()); setSource(next); if (!next.eligible) setError(next.ineligibleReason ?? '此來源不可沖銷。'); } catch (caught) { setError(caught instanceof Error ? caught.message : '來源查詢失敗。'); } }
  function submit(event: FormEvent) { event.preventDefault(); if (!positive(form.amount) || !form.reason.trim()) { setError('請輸入正數數量及原因。'); return; } if (type === 'BUSINESS_REVERSAL' && (!source?.eligible || new DecimalComparison(source.remainingReversible ?? '0', form.amount).isLess)) { setError('請先取得可用來源，且本次數量不可超過剩餘可沖回額。'); return; } if (type !== 'BUSINESS_REVERSAL' && (!form.userId?.trim() || !form.assetSymbol || !form.direction)) { setError('請完整填寫使用者、帳戶、資產與方向。'); return; } if ((Boolean(form.sourceBusinessType?.trim())) !== (Boolean(form.sourceBusinessId?.trim()))) { setError('關聯業務必須同時填寫類型與 ID。'); return; } setError(null); setConfirming(true); }
  async function confirm() { setConfirming(false); setSubmitting(true); try { const request: AdminAssetAdjustmentRequest = type === 'BUSINESS_REVERSAL' ? { adjustmentType:type, sourceLedgerEntryId:source?.ledgerEntryId, amount:form.amount, reason:form.reason, incidentReference:form.incidentReference || undefined, sourceBusinessType:form.sourceBusinessType || undefined, sourceBusinessId:form.sourceBusinessId || undefined } : { ...form, adjustmentType:type, sourceBusinessType:form.sourceBusinessType || undefined, sourceBusinessId:form.sourceBusinessId || undefined, incidentReference:form.incidentReference || undefined }; const response=await createAdminAssetAdjustment(request, crypto.randomUUID()); setResult(`調整已完成，Journal #${response.ledgerJournalId}${response.replayed ? '（安全重送）' : ''}`); } catch (caught) { setError(caught instanceof Error ? caught.message : '資產調整未完成。'); } finally { setSubmitting(false); } }
  return <section className="admin-airdrop-form" aria-label="資產沖銷與調整"><form className="admin-airdrop-form__body" onSubmit={submit} noValidate>
    <section className="admin-airdrop-form__section"><h2>資產沖銷／調整</h2><p>人工修正與系統補償可以沒有業務來源；業務沖銷必須從已發生的使用者 Ledger effect 開始。</p><label className="field"><span className="field__label">調整類型 *</span><select className="input" value={type} onChange={(e) => choose(e.target.value as AssetAdjustmentType)}><option value="MANUAL_CORRECTION">人工修正</option><option value="BUSINESS_REVERSAL">業務沖銷</option><option value="COMPENSATION">系統補償</option></select></label></section>
    {type === 'BUSINESS_REVERSAL' ? <section className="admin-airdrop-form__section"><label className="field"><span className="field__label">原始帳本紀錄 ID *</span><input className="input" value={sourceId} onChange={(e)=>setSourceId(e.target.value)} /></label><button className="secondary-button" type="button" onClick={() => void lookup()}>解析來源</button>{source ? <dl className="admin-airdrop-form__confirmation"><div><dt>使用者</dt><dd>{source.userEmail ?? source.userId}</dd></div><div><dt>帳戶／資產</dt><dd>{source.accountType}／{source.assetSymbol}</dd></div><div><dt>原始影響</dt><dd>{source.originalDirection === 'CREDIT' ? '補入' : '扣回'} {source.originalAmount}</dd></div><div><dt>已沖銷／剩餘可沖銷數量</dt><dd>{source.alreadyReversed}／{source.remainingReversible}</dd></div></dl> : null}</section> : <section className="admin-airdrop-form__section"><div className="admin-airdrop-form__grid"><label className="field"><span className="field__label">方向 *</span><select className="input" value={form.direction} onChange={(e)=>change('direction',e.target.value as 'CREDIT'|'DEBIT')}><option value="CREDIT">補入</option><option value="DEBIT">扣回</option></select></label><label className="field"><span className="field__label">使用者 *</span><input className="input" value={form.userId} onChange={(e)=>change('userId',e.target.value)} /></label><label className="field"><span className="field__label">帳戶 *</span><input className="input" value="SPOT" readOnly /></label><label className="field"><span className="field__label">資產 *</span><select className="input" value={form.assetSymbol} onChange={(e)=>change('assetSymbol',e.target.value)}>{assets.map((a)=><option key={a.assetSymbol} value={a.assetSymbol}>{a.assetSymbol}</option>)}</select></label></div></section>}
    <section className="admin-airdrop-form__section"><div className="admin-airdrop-form__grid"><label className="field"><span className="field__label">數量 *</span><input className="input" inputMode="decimal" value={form.amount} onChange={(e)=>change('amount',e.target.value)} placeholder="只接受正數" /></label><label className="field"><span className="field__label">事件／工單編號（選填）</span><input className="input" value={form.incidentReference ?? ''} onChange={(e)=>change('incidentReference',e.target.value)} /></label><label className="field"><span className="field__label">來源業務類型（選填）</span><input className="input" value={form.sourceBusinessType ?? ''} onChange={(e)=>change('sourceBusinessType',e.target.value)} /></label><label className="field"><span className="field__label">來源業務 ID（選填）</span><input className="input" value={form.sourceBusinessId ?? ''} onChange={(e)=>change('sourceBusinessId',e.target.value)} /></label></div><label className="field"><span className="field__label">原因 *</span><textarea className="input" maxLength={256} value={form.reason} onChange={(e)=>change('reason',e.target.value)} /></label></section>
    <div className="admin-airdrop-form__actions"><button className="primary-button admin-airdrop-form__submit" disabled={submitting} type="submit">{submitting ? '處理中' : type === 'BUSINESS_REVERSAL' ? '確認沖銷' : '確認調整'}</button></div>{error ? <p className="admin-airdrop-form__feedback admin-airdrop-form__feedback--error" role="alert">{error}</p> : null}{result ? <p className="admin-airdrop-form__feedback admin-airdrop-form__feedback--success" role="status">{result}</p> : null}
  </form><ConfirmDialog open={confirming} title={type === 'BUSINESS_REVERSAL' ? '確認業務沖銷' : '確認資產調整'} description="提交後將以 append-only ledger 建立新的 compensating entries。" confirmLabel={type === 'BUSINESS_REVERSAL' ? '確認沖銷' : '確認調整'} cancelLabel="取消" onCancel={()=>setConfirming(false)} onConfirm={()=>void confirm()}><dl className="admin-airdrop-form__confirmation"><div><dt>類型</dt><dd>{type}</dd></div><div><dt>數量</dt><dd>{form.amount} {type === 'BUSINESS_REVERSAL' ? source?.assetSymbol : form.assetSymbol}</dd></div><div><dt>原因</dt><dd>{form.reason}</dd></div></dl></ConfirmDialog></section>;
}

/** 僅比較 decimal string 的位數，不把金融數值轉成 JavaScript Number。 */
class DecimalComparison { readonly isLess: boolean; constructor(left: string, right: string) { const [li,lf='']=left.split('.'); const [ri,rf='']=right.split('.'); const scale=Math.max(lf.length,rf.length); const normalize=(i:string,f:string)=>`${i.replace(/^0+(?=\d)/,'')}${f.padEnd(scale,'0')}`; const a=normalize(li,lf); const b=normalize(ri,rf); this.isLess=a.length!==b.length ? a.length<b.length : a<b; } }
