spring:
  application:
    name: java21-exchange   # ??????? Spring context ??????
  profiles:
    active: dev   # ???? dev profile???????

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration   # ??????????????? profile ???
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration # ???? JPA ????
