CREATE TABLE users (
    user_id VARCHAR(64) PRIMARY KEY,
    email VARCHAR(320) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'))
);

CREATE TABLE accounts (
    account_id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    account_type VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_accounts_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_accounts_user_type UNIQUE (user_id, account_type),
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('SPOT', 'FUTURES', 'MARGIN')),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE INDEX idx_accounts_user_id ON accounts (user_id);

CREATE TABLE assets (
    asset_symbol VARCHAR(32) PRIMARY KEY,
    display_name VARCHAR(128) NOT NULL,
    precision_scale SMALLINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_assets_precision_scale CHECK (precision_scale BETWEEN 0 AND 18),
    CONSTRAINT ck_assets_status CHECK (status IN ('ACTIVE', 'HALTED', 'DELISTED'))
);

CREATE TABLE markets (
    market_symbol VARCHAR(32) PRIMARY KEY,
    base_asset_symbol VARCHAR(32) NOT NULL,
    quote_asset_symbol VARCHAR(32) NOT NULL,
    price_scale SMALLINT NOT NULL,
    quantity_scale SMALLINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_markets_base_asset_symbol
        FOREIGN KEY (base_asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT fk_markets_quote_asset_symbol
        FOREIGN KEY (quote_asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT uq_markets_pair UNIQUE (base_asset_symbol, quote_asset_symbol),
    CONSTRAINT ck_markets_asset_pair CHECK (base_asset_symbol <> quote_asset_symbol),
    CONSTRAINT ck_markets_price_scale CHECK (price_scale BETWEEN 0 AND 18),
    CONSTRAINT ck_markets_quantity_scale CHECK (quantity_scale BETWEEN 0 AND 18),
    CONSTRAINT ck_markets_status CHECK (status IN ('ACTIVE', 'HALTED', 'CLOSED'))
);

CREATE INDEX idx_markets_base_asset_symbol ON markets (base_asset_symbol);
CREATE INDEX idx_markets_quote_asset_symbol ON markets (quote_asset_symbol);

CREATE TABLE account_assets (
    account_asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(64) NOT NULL,
    asset_symbol VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account_assets_account_id
        FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    CONSTRAINT fk_account_assets_asset_symbol
        FOREIGN KEY (asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT uq_account_assets_account_asset UNIQUE (account_id, asset_symbol),
    CONSTRAINT ck_account_assets_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_account_assets_account_id ON account_assets (account_id);
CREATE INDEX idx_account_assets_asset_symbol ON account_assets (asset_symbol);
