-- P12-T02: Identity, account, asset, market foundation schema.
-- 本 migration 只建立使用者、帳戶、資產、交易對與帳戶資產關聯的基礎資料表。
-- 本 migration 不建立 ledger、reservation、orders、trades、deposits、withdrawals。
-- 本 migration 不實作任何 runtime money movement。

-- 使用者身分主檔。
-- 保存登入與帳戶歸屬所需的基本識別資料；不保存資金、帳本、訂單或交易狀態。
CREATE TABLE users (
    -- 使用者唯一識別碼。由應用層產生。
    user_id VARCHAR(64) PRIMARY KEY,

    -- 使用者電子郵件。必須唯一。
    email VARCHAR(320) NOT NULL,

    -- 使用者顯示名稱。僅供介面與管理後台顯示，不應作為安全或交易判斷依據。
    display_name VARCHAR(128) NOT NULL,

    -- 使用者狀態。ACTIVE 表示可正常使用；SUSPENDED 表示暫停；CLOSED 表示關閉。
    status VARCHAR(16) NOT NULL,

    -- 資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED'))
);

-- 使用者帳戶容器。
-- 用來區分 SPOT、FUTURES、MARGIN 等帳戶類型；本表不保存餘額，不處理資金異動。
CREATE TABLE accounts (
    -- 帳戶唯一識別碼。由應用層產生。
    account_id VARCHAR(64) PRIMARY KEY,

    -- 帳戶所屬使用者。關聯 users.user_id。
    user_id VARCHAR(64) NOT NULL,

    -- 帳戶類型。SPOT 為現貨帳戶；FUTURES 為合約帳戶；MARGIN 為槓桿帳戶。
    account_type VARCHAR(16) NOT NULL,

    -- 帳戶狀態。ACTIVE 表示可用；FROZEN 表示凍結；CLOSED 表示關閉。
    status VARCHAR(16) NOT NULL,

    -- 資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_accounts_user_id
        FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uq_accounts_user_type UNIQUE (user_id, account_type),
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('SPOT', 'FUTURES', 'MARGIN')),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

-- 依 user_id 查詢使用者帳戶。
CREATE INDEX idx_accounts_user_id ON accounts (user_id);

-- 資產主檔。
-- 定義系統支援的資產，例如 BTC、ETH、USDT；不保存使用者餘額或鏈上交易資料。
CREATE TABLE assets (
    -- 資產代號，例如 BTC、ETH、USDT。作為資產主檔的主鍵。
    asset_symbol VARCHAR(32) PRIMARY KEY,

    -- 資產顯示名稱，例如 Bitcoin、Ethereum、Tether USD。
    display_name VARCHAR(128) NOT NULL,

    -- 資產數量精度。代表該資產可支援的小數位數，範圍為 0 到 18。
    precision_scale SMALLINT NOT NULL,

    -- 資產狀態。ACTIVE 表示可用；HALTED 表示暫停；DELISTED 表示下架。
    status VARCHAR(16) NOT NULL,

    -- 資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_assets_precision_scale CHECK (precision_scale BETWEEN 0 AND 18),
    CONSTRAINT ck_assets_status CHECK (status IN ('ACTIVE', 'HALTED', 'DELISTED'))
);

-- 交易對主檔。
-- 定義可交易的 base / quote 資產組合與價格、數量精度；不保存行情快照、成交量或撮合狀態。
CREATE TABLE markets (
    -- 交易對代號，例如 BTC-USDT。作為交易對主檔的主鍵。
    market_symbol VARCHAR(32) PRIMARY KEY,

    -- 交易對的 base asset，例如 BTC-USDT 中的 BTC。關聯 assets.asset_symbol。
    base_asset_symbol VARCHAR(32) NOT NULL,

    -- 交易對的 quote asset，例如 BTC-USDT 中的 USDT。關聯 assets.asset_symbol。
    quote_asset_symbol VARCHAR(32) NOT NULL,

    -- 價格精度。代表該交易對價格允許的小數位數，範圍為 0 到 18。
    price_scale SMALLINT NOT NULL,

    -- 數量精度。代表該交易對下單數量允許的小數位數，範圍為 0 到 18。
    quantity_scale SMALLINT NOT NULL,

    -- 交易對狀態。ACTIVE 表示可交易；HALTED 表示暫停；CLOSED 表示關閉。
    status VARCHAR(16) NOT NULL,

    -- 資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_markets_base_asset_symbol
        FOREIGN KEY (base_asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT fk_markets_quote_asset_symbol
        FOREIGN KEY (quote_asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT uq_markets_pair UNIQUE (base_asset_symbol, quote_asset_symbol),
    CONSTRAINT ck_markets_asset_pair CHECK (base_asset_symbol <> quote_asset_symbol),
    CONSTRAINT ck_markets_price_scale CHECK (price_scale BETWEEN 0 AND 18),
    CONSTRAINT ck_markets_quantity_scale CHECK (quantity_scale BETWEEN 0 AND 18),
    CONSTRAINT ck_markets_status CHECK (status IN ('ACTIVE', 'HALTED', 'CLOSED'))
);

-- 依 base asset 查詢交易對。
CREATE INDEX idx_markets_base_asset_symbol ON markets (base_asset_symbol);

-- 依 quote asset 查詢交易對。
CREATE INDEX idx_markets_quote_asset_symbol ON markets (quote_asset_symbol);

-- 帳戶與資產的基礎關聯表。
-- 表示某帳戶可關聯某資產；不保存 available、locked、reserved 或 total balance。
CREATE TABLE account_assets (
    -- 帳戶資產關聯唯一識別碼。由資料庫 identity 產生。
    account_asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 帳戶識別碼。關聯 accounts.account_id。
    account_id VARCHAR(64) NOT NULL,

    -- 資產代號。關聯 assets.asset_symbol。
    asset_symbol VARCHAR(32) NOT NULL,

    -- 帳戶資產關聯狀態。ACTIVE 表示可用；INACTIVE 表示停用。
    status VARCHAR(16) NOT NULL,

    -- 資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_account_assets_account_id
        FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    CONSTRAINT fk_account_assets_asset_symbol
        FOREIGN KEY (asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT uq_account_assets_account_asset UNIQUE (account_id, asset_symbol),
    CONSTRAINT ck_account_assets_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- 依 account_id 查詢帳戶資產關聯。
CREATE INDEX idx_account_assets_account_id ON account_assets (account_id);

-- 依 asset_symbol 查詢帳戶資產關聯。
CREATE INDEX idx_account_assets_asset_symbol ON account_assets (asset_symbol);


-- PostgreSQL database comments.
-- 這些註解會寫入 PostgreSQL metadata，可由 psql、DBeaver、DataGrip 等工具讀取。

COMMENT ON TABLE users IS
'使用者身分主檔。保存登入與帳戶歸屬所需的基本識別資料；不保存資金、帳本、訂單或交易狀態。';

COMMENT ON COLUMN users.user_id IS
'使用者唯一識別碼。由應用層產生，作為其他帳戶與身分相關資料的外鍵目標。';

COMMENT ON COLUMN users.email IS
'使用者電子郵件。必須唯一；可作為登入識別或通知地址，但不應直接承載權限或 KYC 狀態。';

COMMENT ON COLUMN users.display_name IS
'使用者顯示名稱。僅供介面與管理後台顯示，不應作為安全或交易判斷依據。';

COMMENT ON COLUMN users.status IS
'使用者狀態。ACTIVE 表示可正常使用；SUSPENDED 表示暫停；CLOSED 表示關閉。';

COMMENT ON COLUMN users.created_at IS
'資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。';

COMMENT ON COLUMN users.updated_at IS
'資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。';


COMMENT ON TABLE accounts IS
'使用者帳戶容器。用來區分 SPOT、FUTURES、MARGIN 等帳戶類型；本表不保存餘額，不處理資金異動。';

COMMENT ON COLUMN accounts.account_id IS
'帳戶唯一識別碼。由應用層產生。';

COMMENT ON COLUMN accounts.user_id IS
'帳戶所屬使用者。關聯 users.user_id。';

COMMENT ON COLUMN accounts.account_type IS
'帳戶類型。SPOT 為現貨帳戶；FUTURES 為合約帳戶；MARGIN 為槓桿帳戶。';

COMMENT ON COLUMN accounts.status IS
'帳戶狀態。ACTIVE 表示可用；FROZEN 表示凍結；CLOSED 表示關閉。';

COMMENT ON COLUMN accounts.created_at IS
'資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。';

COMMENT ON COLUMN accounts.updated_at IS
'資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。';


COMMENT ON TABLE assets IS
'資產主檔。定義系統支援的資產，例如 BTC、ETH、USDT；不保存使用者餘額或鏈上交易資料。';

COMMENT ON COLUMN assets.asset_symbol IS
'資產代號，例如 BTC、ETH、USDT。作為資產主檔的主鍵。';

COMMENT ON COLUMN assets.display_name IS
'資產顯示名稱，例如 Bitcoin、Ethereum、Tether USD。';

COMMENT ON COLUMN assets.precision_scale IS
'資產數量精度。代表該資產可支援的小數位數，範圍為 0 到 18。';

COMMENT ON COLUMN assets.status IS
'資產狀態。ACTIVE 表示可用；HALTED 表示暫停；DELISTED 表示下架。';

COMMENT ON COLUMN assets.created_at IS
'資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。';

COMMENT ON COLUMN assets.updated_at IS
'資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。';


COMMENT ON TABLE markets IS
'交易對主檔。定義可交易的 base / quote 資產組合與價格、數量精度；不保存行情快照、成交量或撮合狀態。';

COMMENT ON COLUMN markets.market_symbol IS
'交易對代號，例如 BTC-USDT。作為交易對主檔的主鍵。';

COMMENT ON COLUMN markets.base_asset_symbol IS
'交易對的 base asset，例如 BTC-USDT 中的 BTC。關聯 assets.asset_symbol。';

COMMENT ON COLUMN markets.quote_asset_symbol IS
'交易對的 quote asset，例如 BTC-USDT 中的 USDT。關聯 assets.asset_symbol。';

COMMENT ON COLUMN markets.price_scale IS
'價格精度。代表該交易對價格允許的小數位數，範圍為 0 到 18。';

COMMENT ON COLUMN markets.quantity_scale IS
'數量精度。代表該交易對下單數量允許的小數位數，範圍為 0 到 18。';

COMMENT ON COLUMN markets.status IS
'交易對狀態。ACTIVE 表示可交易；HALTED 表示暫停；CLOSED 表示關閉。';

COMMENT ON COLUMN markets.created_at IS
'資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。';

COMMENT ON COLUMN markets.updated_at IS
'資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。';


COMMENT ON TABLE account_assets IS
'帳戶與資產的基礎關聯表。表示某帳戶可關聯某資產；不保存 available、locked、reserved 或 total balance。';

COMMENT ON COLUMN account_assets.account_asset_id IS
'帳戶資產關聯唯一識別碼。由資料庫 identity 產生。';

COMMENT ON COLUMN account_assets.account_id IS
'帳戶識別碼。關聯 accounts.account_id。';

COMMENT ON COLUMN account_assets.asset_symbol IS
'資產代號。關聯 assets.asset_symbol。';

COMMENT ON COLUMN account_assets.status IS
'帳戶資產關聯狀態。ACTIVE 表示可用；INACTIVE 表示停用。';

COMMENT ON COLUMN account_assets.created_at IS
'資料建立時間。由資料庫預設 CURRENT_TIMESTAMP 產生。';

COMMENT ON COLUMN account_assets.updated_at IS
'資料最後更新時間。此欄位不會自動更新，需由應用層或後續 migration trigger 維護。';