-- Balance projections are the query-facing snapshot of account balances.
-- They must remain rebuildable from ledger data once ledger tables exist.
CREATE TABLE balance_projections (
    balance_projection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id VARCHAR(64) NOT NULL,
    asset_symbol VARCHAR(32) NOT NULL,
    total_amount NUMERIC(36, 18) NOT NULL DEFAULT 0,
    available_amount NUMERIC(36, 18) NOT NULL DEFAULT 0,
    locked_amount NUMERIC(36, 18) NOT NULL DEFAULT 0,
    projection_version BIGINT NOT NULL DEFAULT 0,
    projected_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reconciled_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_balance_projections_account_id
        FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    CONSTRAINT fk_balance_projections_asset_symbol
        FOREIGN KEY (asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT uq_balance_projections_account_asset UNIQUE (account_id, asset_symbol),
    CONSTRAINT ck_balance_projections_amounts_non_negative
        CHECK (total_amount >= 0 AND available_amount >= 0 AND locked_amount >= 0),
    CONSTRAINT ck_balance_projections_total_matches_components
        CHECK (total_amount = available_amount + locked_amount),
    CONSTRAINT ck_balance_projections_projection_version CHECK (projection_version >= 0)
);

COMMENT ON TABLE balance_projections IS 'Account balance read model for query-side balance projection and reconciliation.';
COMMENT ON COLUMN balance_projections.balance_projection_id IS 'Surrogate identifier for the balance projection row.';
COMMENT ON COLUMN balance_projections.account_id IS 'Reference to the owning account.';
COMMENT ON COLUMN balance_projections.asset_symbol IS 'Reference to the asset whose balance is projected.';
COMMENT ON COLUMN balance_projections.total_amount IS 'Projected total balance for the account and asset.';
COMMENT ON COLUMN balance_projections.available_amount IS 'Projected available balance that is not locked.';
COMMENT ON COLUMN balance_projections.locked_amount IS 'Projected locked balance held for orders or withdrawals.';
COMMENT ON COLUMN balance_projections.projection_version IS 'Monotonic version of the projection row for rebuild and replay checks.';
COMMENT ON COLUMN balance_projections.projected_at IS 'Timestamp when the balance projection was last refreshed.';
COMMENT ON COLUMN balance_projections.reconciled_at IS 'Timestamp when the row was last reconciled against source data.';

CREATE INDEX idx_balance_projections_account_id ON balance_projections (account_id);
CREATE INDEX idx_balance_projections_asset_symbol ON balance_projections (asset_symbol);
CREATE INDEX idx_balance_projections_reconciled_at ON balance_projections (reconciled_at);
