-- Ledger journals are immutable business-event headers.
-- Ledger entries are append-only double-entry lines tied to a journal.
CREATE TABLE ledger_journals (
    ledger_journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_reference_type VARCHAR(32) NOT NULL,
    business_reference_id VARCHAR(128) NOT NULL,
    request_id VARCHAR(64),
    journal_note VARCHAR(256),
    posted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_ledger_journals_reference_type
        CHECK (business_reference_type IN ('DEPOSIT', 'WITHDRAWAL', 'ORDER', 'TRADE', 'SETTLEMENT', 'FEE', 'ADJUSTMENT'))
);

COMMENT ON TABLE ledger_journals IS 'Immutable journal header for ledger business events.';
COMMENT ON COLUMN ledger_journals.ledger_journal_id IS 'Surrogate identifier for the journal header.';
COMMENT ON COLUMN ledger_journals.business_reference_type IS 'Business event category such as deposit, withdrawal, order, trade, settlement, fee, or adjustment.';
COMMENT ON COLUMN ledger_journals.business_reference_id IS 'Business-side reference identifier for the source event or aggregate.';
COMMENT ON COLUMN ledger_journals.request_id IS 'Optional request identifier for idempotency or audit correlation.';
COMMENT ON COLUMN ledger_journals.journal_note IS 'Optional human-readable note for audit and operations.';
COMMENT ON COLUMN ledger_journals.posted_at IS 'Business timestamp when the journal was posted.';
COMMENT ON COLUMN ledger_journals.created_at IS 'Database timestamp when the journal row was created.';

CREATE INDEX idx_ledger_journals_posted_at ON ledger_journals (posted_at);
CREATE INDEX idx_ledger_journals_reference ON ledger_journals (business_reference_type, business_reference_id);
CREATE INDEX idx_ledger_journals_request_id ON ledger_journals (request_id);

CREATE TABLE ledger_entries (
    ledger_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ledger_journal_id BIGINT NOT NULL,
    entry_sequence INTEGER NOT NULL,
    account_id VARCHAR(64) NOT NULL,
    asset_symbol VARCHAR(32) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    amount NUMERIC(36, 18) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ledger_entries_ledger_journal_id
        FOREIGN KEY (ledger_journal_id) REFERENCES ledger_journals (ledger_journal_id),
    CONSTRAINT fk_ledger_entries_account_id
        FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    CONSTRAINT fk_ledger_entries_asset_symbol
        FOREIGN KEY (asset_symbol) REFERENCES assets (asset_symbol),
    CONSTRAINT uq_ledger_entries_journal_sequence UNIQUE (ledger_journal_id, entry_sequence),
    CONSTRAINT ck_ledger_entries_sequence_positive CHECK (entry_sequence > 0),
    CONSTRAINT ck_ledger_entries_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_ledger_entries_amount_positive CHECK (amount > 0)
);

COMMENT ON TABLE ledger_entries IS 'Append-only double-entry lines for each immutable ledger journal.';
COMMENT ON COLUMN ledger_entries.ledger_entry_id IS 'Surrogate identifier for the ledger line item.';
COMMENT ON COLUMN ledger_entries.ledger_journal_id IS 'Reference to the immutable journal header that groups this entry.';
COMMENT ON COLUMN ledger_entries.entry_sequence IS 'Journal-local sequence number for deterministic entry ordering.';
COMMENT ON COLUMN ledger_entries.account_id IS 'Reference to the account affected by this entry.';
COMMENT ON COLUMN ledger_entries.asset_symbol IS 'Reference to the asset affected by this entry.';
COMMENT ON COLUMN ledger_entries.direction IS 'Debit or credit direction for double-entry accounting.';
COMMENT ON COLUMN ledger_entries.amount IS 'Positive monetary amount for the entry.';
COMMENT ON COLUMN ledger_entries.created_at IS 'Database timestamp when the entry row was created.';

CREATE INDEX idx_ledger_entries_journal_id ON ledger_entries (ledger_journal_id);
CREATE INDEX idx_ledger_entries_account_id ON ledger_entries (account_id);
CREATE INDEX idx_ledger_entries_asset_symbol ON ledger_entries (asset_symbol);
CREATE INDEX idx_ledger_entries_direction ON ledger_entries (direction);
