-- P12-T06: Wallet lifecycle schema for deposit, withdrawal, address, and chain transaction records.
-- 這份 migration 只建立錢包生命週期資料結構，供後續對帳與查詢使用。
-- 不實作鏈上監聽、入金入帳、提款簽章、廣播或任何 runtime money movement。
-- Rollback 注意事項：若要回滾，必須先確認沒有後續資料依賴這些表；刪除順序應為 withdrawals、deposits、chain_transactions、deposit_addresses。

-- 使用者入金地址主檔。
-- 這只是一份可查詢的 address registry，不代表地址已被入帳，也不代表地址私鑰由本系統持有。
CREATE TABLE deposit_addresses (
    -- 入金地址唯一識別碼。由資料庫產生，避免地址輪替時需要改動外部引用。
    deposit_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 所屬帳戶。使用 account 作為邊界，避免把地址直接綁死在使用者層級。
    account_id VARCHAR(64) NOT NULL,

    -- 所屬資產。與 account_id 共同構成可用的資產範圍，必須與 account_assets 保持一致。
    asset_symbol VARCHAR(32) NOT NULL,

    -- 鏈別，例如 ERC20、TRC20、BTC、SOL。這只代表地址所在網路，不代表任何鏈上事件已確認。
    chain_type VARCHAR(16) NOT NULL,

    -- 入金地址字串。只保存可供查詢的地址內容，不保存密鑰或簽章材料。
    address VARCHAR(256) NOT NULL,

    -- 地址標籤或備註。部分鏈或業務場景需要額外標記，但這不應承載安全判斷。
    address_label VARCHAR(128),

    -- 地址狀態。ACTIVE 表示可用；DISABLED 表示停用；ARCHIVED 表示歷史保留。
    status VARCHAR(16) NOT NULL,

    -- 資料建立時間。由資料庫預設產生，供審計與對帳使用。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。地址輪替或狀態變更時由應用層維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_deposit_addresses_account_asset
        FOREIGN KEY (account_id, asset_symbol) REFERENCES account_assets (account_id, asset_symbol),
    CONSTRAINT ck_deposit_addresses_chain_type CHECK (chain_type IN ('TRC20', 'ERC20', 'BTC', 'SOL')),
    CONSTRAINT ck_deposit_addresses_status CHECK (status IN ('ACTIVE', 'DISABLED', 'ARCHIVED')),
    CONSTRAINT uq_deposit_addresses_chain_address UNIQUE (chain_type, address),
    CONSTRAINT uq_deposit_addresses_account_asset_chain UNIQUE (account_id, asset_symbol, chain_type)
);

CREATE INDEX idx_deposit_addresses_account_id ON deposit_addresses (account_id);
CREATE INDEX idx_deposit_addresses_asset_symbol ON deposit_addresses (asset_symbol);
CREATE INDEX idx_deposit_addresses_status ON deposit_addresses (status);

COMMENT ON TABLE deposit_addresses IS
'使用者入金地址主檔。這只是一份可查詢的 address registry，不代表地址已被入帳，也不代表地址私鑰由本系統持有。';

COMMENT ON COLUMN deposit_addresses.deposit_address_id IS
'入金地址唯一識別碼。由資料庫產生，避免地址輪替時需要改動外部引用。';

COMMENT ON COLUMN deposit_addresses.account_id IS
'所屬帳戶。使用 account 作為邊界，避免把地址直接綁死在使用者層級。';

COMMENT ON COLUMN deposit_addresses.asset_symbol IS
'所屬資產。與 account_id 共同構成可用的資產範圍，必須與 account_assets 保持一致。';

COMMENT ON COLUMN deposit_addresses.chain_type IS
'鏈別，例如 ERC20、TRC20、BTC、SOL。這只代表地址所在網路，不代表任何鏈上事件已確認。';

COMMENT ON COLUMN deposit_addresses.address IS
'入金地址字串。只保存可供查詢的地址內容，不保存密鑰或簽章材料。';

COMMENT ON COLUMN deposit_addresses.address_label IS
'地址標籤或備註。部分鏈或業務場景需要額外標記，但這不應承載安全判斷。';

COMMENT ON COLUMN deposit_addresses.status IS
'地址狀態。ACTIVE 表示可用；DISABLED 表示停用；ARCHIVED 表示歷史保留。';

COMMENT ON COLUMN deposit_addresses.created_at IS
'資料建立時間。由資料庫預設產生，供審計與對帳使用。';

COMMENT ON COLUMN deposit_addresses.updated_at IS
'資料最後更新時間。地址輪替或狀態變更時由應用層維護。';

-- 鏈上交易主檔。
-- 這是 chain observer 的可查詢結果，不是 ledger source of truth，也不是入帳完成證明。
CREATE TABLE chain_transactions (
    -- 鏈上交易唯一識別碼。由資料庫產生，供本地關聯與對帳。
    chain_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 鏈別。這決定 tx hash 的命名空間，不同鏈不能混用相同 hash 做唯一性判斷。
    chain_type VARCHAR(16) NOT NULL,

    -- 交易類型。DEPOSIT / WITHDRAWAL 只描述這筆鏈上交易對應的業務方向。
    transaction_type VARCHAR(16) NOT NULL,

    -- 鏈上交易哈希。這是鏈層唯一識別碼，必須保留以便查詢與對帳。
    tx_hash VARCHAR(128) NOT NULL,

    -- 區塊哈希。僅供追溯；交易仍可能因 reorg 或確認政策而改變業務狀態。
    block_hash VARCHAR(128),

    -- 區塊高度。僅供觀測與查詢，不代表本地資金狀態已完成更新。
    block_height BIGINT,

    -- 發送地址。這是觀測欄位，不是授權來源，也不代表風控已通過。
    from_address VARCHAR(256),

    -- 收款地址。對入金而言通常對應 deposit address；對提款而言則代表外部收款方。
    to_address VARCHAR(256),

    -- 鏈上金額。使用 NUMERIC(38, 18) 避免 binary floating point 誤差。
    amount NUMERIC(38, 18) NOT NULL,

    -- 鏈上手續費。這是觀測欄位，不能直接拿來當作正式扣費規則。
    fee_amount NUMERIC(38, 18) NOT NULL DEFAULT 0,

    -- 鏈上交易狀態。只描述觀測與確認層級，不代表本地帳務已完成。
    status VARCHAR(16) NOT NULL,

    -- 最早觀測時間。用來區分 observer 看到交易與業務完成入帳之間的時間差。
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 確認時間。只有在確認政策滿足時才會填值；這不等於入帳完成。
    confirmed_at TIMESTAMP WITH TIME ZONE,

    -- 資料建立時間。由資料庫預設產生，供審計與對帳使用。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。狀態修正或重新對帳時由應用層維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_chain_transactions_chain_type CHECK (chain_type IN ('TRC20', 'ERC20', 'BTC', 'SOL')),
    CONSTRAINT ck_chain_transactions_transaction_type CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT ck_chain_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_chain_transactions_fee_non_negative CHECK (fee_amount >= 0),
    CONSTRAINT ck_chain_transactions_status CHECK (status IN ('OBSERVED', 'CONFIRMED', 'FAILED', 'REORGED', 'IGNORED')),
    CONSTRAINT uq_chain_transactions_chain_tx_hash UNIQUE (chain_type, tx_hash)
);

CREATE INDEX idx_chain_transactions_chain_type_status ON chain_transactions (chain_type, status);
CREATE INDEX idx_chain_transactions_observed_at ON chain_transactions (observed_at);
CREATE INDEX idx_chain_transactions_confirmed_at ON chain_transactions (confirmed_at);

COMMENT ON TABLE chain_transactions IS
'鏈上交易主檔。這是 chain observer 的可查詢結果，不是 ledger source of truth，也不是入帳完成證明。';

COMMENT ON COLUMN chain_transactions.chain_transaction_id IS
'鏈上交易唯一識別碼。由資料庫產生，供本地關聯與對帳。';

COMMENT ON COLUMN chain_transactions.chain_type IS
'鏈別。這決定 tx hash 的命名空間，不同鏈不能混用相同 hash 做唯一性判斷。';

COMMENT ON COLUMN chain_transactions.transaction_type IS
'交易類型。DEPOSIT / WITHDRAWAL 只描述這筆鏈上交易對應的業務方向。';

COMMENT ON COLUMN chain_transactions.tx_hash IS
'鏈上交易哈希。這是鏈層唯一識別碼，必須保留以便查詢與對帳。';

COMMENT ON COLUMN chain_transactions.block_hash IS
'區塊哈希。僅供追溯；交易仍可能因 reorg 或確認政策而改變業務狀態。';

COMMENT ON COLUMN chain_transactions.block_height IS
'區塊高度。僅供觀測與查詢，不代表本地資金狀態已完成更新。';

COMMENT ON COLUMN chain_transactions.from_address IS
'發送地址。這是觀測欄位，不是授權來源，也不代表風控已通過。';

COMMENT ON COLUMN chain_transactions.to_address IS
'收款地址。對入金而言通常對應 deposit address；對提款而言則代表外部收款方。';

COMMENT ON COLUMN chain_transactions.amount IS
'鏈上金額。使用 NUMERIC(38, 18) 避免 binary floating point 誤差。';

COMMENT ON COLUMN chain_transactions.fee_amount IS
'鏈上手續費。這是觀測欄位，不能直接拿來當作正式扣費規則。';

COMMENT ON COLUMN chain_transactions.status IS
'鏈上交易狀態。只描述觀測與確認層級，不代表本地帳務已完成。';

COMMENT ON COLUMN chain_transactions.observed_at IS
'最早觀測時間。用來區分 observer 看到交易與業務完成入帳之間的時間差。';

COMMENT ON COLUMN chain_transactions.confirmed_at IS
'確認時間。只有在確認政策滿足時才會填值；這不等於入帳完成。';

COMMENT ON COLUMN chain_transactions.created_at IS
'資料建立時間。由資料庫預設產生，供審計與對帳使用。';

COMMENT ON COLUMN chain_transactions.updated_at IS
'資料最後更新時間。狀態修正或重新對帳時由應用層維護。';

-- 充值紀錄。
-- 這只保存入金流程的查詢結果，不代表鏈上觀測一出現就已經完成 credit。
CREATE TABLE deposits (
    -- 充值唯一識別碼。由應用層或上游流程產生，便於操作與對帳。
    deposit_id VARCHAR(64) PRIMARY KEY,

    -- 所屬帳戶。入金最終是落到哪個 account，必須能直接查詢。
    account_id VARCHAR(64) NOT NULL,

    -- 所屬資產。必須與 account_assets 保持一致，不能讓 deposit 自己決定資產歸屬。
    asset_symbol VARCHAR(32) NOT NULL,

    -- 對應的入金地址。這裡保留可追查的 address reference，方便後續對帳。
    deposit_address_id BIGINT NOT NULL,

    -- 對應的鏈上交易。鏈上交易先被觀測，deposits 只是業務層記錄，不是入帳證明。
    chain_transaction_id BIGINT NOT NULL,

    -- 鏈別。保留查詢便利性，避免每次都 join chain_transactions。
    chain_type VARCHAR(16) NOT NULL,

    -- 充值地址。為了對帳與稽核，保留當時使用的地址字串快照。
    address VARCHAR(256) NOT NULL,

    -- 充值金額。使用 NUMERIC(38, 18) 避免浮點誤差。
    amount NUMERIC(38, 18) NOT NULL,

    -- 已確認數。只做對帳與顯示，不等於已 credit。
    confirmations INTEGER NOT NULL DEFAULT 0,

    -- 充值狀態。只描述入金流程狀態，不代表 ledger 已寫入。
    status VARCHAR(16) NOT NULL,

    -- 入帳時間。只有在後續 credit 完成時才應由應用層填值。
    credited_at TIMESTAMP WITH TIME ZONE,

    -- 資料建立時間。由資料庫預設產生，供審計與對帳使用。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。狀態進展或對帳修正時由應用層維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_deposits_account_asset
        FOREIGN KEY (account_id, asset_symbol) REFERENCES account_assets (account_id, asset_symbol),
    CONSTRAINT fk_deposits_deposit_address_id
        FOREIGN KEY (deposit_address_id) REFERENCES deposit_addresses (deposit_address_id),
    CONSTRAINT fk_deposits_chain_transaction_id
        FOREIGN KEY (chain_transaction_id) REFERENCES chain_transactions (chain_transaction_id),
    CONSTRAINT ck_deposits_chain_type CHECK (chain_type IN ('TRC20', 'ERC20', 'BTC', 'SOL')),
    CONSTRAINT ck_deposits_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_deposits_confirmations_non_negative CHECK (confirmations >= 0),
    CONSTRAINT ck_deposits_status CHECK (status IN ('PENDING', 'CONFIRMING', 'SUCCESS', 'FAILED', 'IGNORED')),
    CONSTRAINT uq_deposits_chain_transaction UNIQUE (chain_transaction_id)
);

CREATE INDEX idx_deposits_account_id ON deposits (account_id);
CREATE INDEX idx_deposits_asset_symbol ON deposits (asset_symbol);
CREATE INDEX idx_deposits_status ON deposits (status);
CREATE INDEX idx_deposits_chain_transaction_id ON deposits (chain_transaction_id);

COMMENT ON TABLE deposits IS
'充值紀錄。這只保存入金流程的查詢結果，不代表鏈上觀測一出現就已經完成 credit。';

COMMENT ON COLUMN deposits.deposit_id IS
'充值唯一識別碼。由應用層或上游流程產生，便於操作與對帳。';

COMMENT ON COLUMN deposits.account_id IS
'所屬帳戶。入金最終是落到哪個 account，必須能直接查詢。';

COMMENT ON COLUMN deposits.asset_symbol IS
'所屬資產。必須與 account_assets 保持一致，不能讓 deposit 自己決定資產歸屬。';

COMMENT ON COLUMN deposits.deposit_address_id IS
'對應的入金地址。這裡保留可追查的 address reference，方便後續對帳。';

COMMENT ON COLUMN deposits.chain_transaction_id IS
'對應的鏈上交易。鏈上交易先被觀測，deposits 只是業務層記錄，不是入帳證明。';

COMMENT ON COLUMN deposits.chain_type IS
'鏈別。保留查詢便利性，避免每次都 join chain_transactions。';

COMMENT ON COLUMN deposits.address IS
'充值地址。為了對帳與稽核，保留當時使用的地址字串快照。';

COMMENT ON COLUMN deposits.amount IS
'充值金額。使用 NUMERIC(38, 18) 避免浮點誤差。';

COMMENT ON COLUMN deposits.confirmations IS
'已確認數。只做對帳與顯示，不等於已 credit。';

COMMENT ON COLUMN deposits.status IS
'充值狀態。只描述入金流程狀態，不代表 ledger 已寫入。';

COMMENT ON COLUMN deposits.credited_at IS
'入帳時間。只有在後續 credit 完成時才應由應用層填值。';

COMMENT ON COLUMN deposits.created_at IS
'資料建立時間。由資料庫預設產生，供審計與對帳使用。';

COMMENT ON COLUMN deposits.updated_at IS
'資料最後更新時間。狀態進展或對帳修正時由應用層維護。';

-- 提現紀錄。
-- 這只保存提款流程的查詢結果，不代表已核准、已簽章或已廣播。
CREATE TABLE withdrawals (
    -- 提現唯一識別碼。由應用層產生，作為操作與稽核主鍵。
    withdrawal_id VARCHAR(64) PRIMARY KEY,

    -- 請求識別碼。這裡只做查詢與重送辨識的輔助欄位，不把它當成完整 idempotency 保證。
    request_id VARCHAR(64) NOT NULL,

    -- 所屬帳戶。提款從哪個 account 出去，必須能直接查詢。
    account_id VARCHAR(64) NOT NULL,

    -- 所屬資產。必須與 account_assets 保持一致。
    asset_symbol VARCHAR(32) NOT NULL,

    -- 鏈別。提款對應哪個網路，會影響地址格式與鏈上費用觀測。
    chain_type VARCHAR(16) NOT NULL,

    -- 收款地址。只保存外部地址字串，不保存任何密鑰或簽章材料。
    address VARCHAR(256) NOT NULL,

    -- 收款地址備註。部分業務或鏈別會需要標記，但不應承載安全判斷。
    address_label VARCHAR(128),

    -- 提現金額。使用 NUMERIC(38, 18) 避免浮點誤差。
    amount NUMERIC(38, 18) NOT NULL,

    -- 手續費。這是展示與對帳欄位，不決定實際扣費策略。
    fee_amount NUMERIC(38, 18) NOT NULL DEFAULT 0,

    -- 對應的鏈上交易。尚未廣播或尚未確認時可為 NULL。
    chain_transaction_id BIGINT,

    -- 提現狀態。這些值只代表流程階段，不代表資金已移出。
    status VARCHAR(24) NOT NULL,

    -- 資料建立時間。由資料庫預設產生，供審計與對帳使用。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。狀態進展、風控或對帳修正時由應用層維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_withdrawals_account_asset
        FOREIGN KEY (account_id, asset_symbol) REFERENCES account_assets (account_id, asset_symbol),
    CONSTRAINT fk_withdrawals_chain_transaction_id
        FOREIGN KEY (chain_transaction_id) REFERENCES chain_transactions (chain_transaction_id),
    CONSTRAINT ck_withdrawals_chain_type CHECK (chain_type IN ('TRC20', 'ERC20', 'BTC', 'SOL')),
    CONSTRAINT ck_withdrawals_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_withdrawals_fee_non_negative CHECK (fee_amount >= 0),
    CONSTRAINT ck_withdrawals_status CHECK (status IN ('SUBMITTED', 'RISK_REVIEW', 'ADMIN_REVIEW', 'APPROVED', 'REJECTED', 'BROADCASTING', 'CHAIN_PENDING', 'SUCCESS', 'FAILED', 'CANCELED')),
    CONSTRAINT uq_withdrawals_request_id UNIQUE (request_id),
    CONSTRAINT uq_withdrawals_chain_transaction UNIQUE (chain_transaction_id)
);

CREATE INDEX idx_withdrawals_account_id ON withdrawals (account_id);
CREATE INDEX idx_withdrawals_asset_symbol ON withdrawals (asset_symbol);
CREATE INDEX idx_withdrawals_status ON withdrawals (status);
CREATE INDEX idx_withdrawals_chain_transaction_id ON withdrawals (chain_transaction_id);

COMMENT ON TABLE withdrawals IS
'提現紀錄。這只保存提款流程的查詢結果，不代表已核准、已簽章或已廣播。';

COMMENT ON COLUMN withdrawals.withdrawal_id IS
'提現唯一識別碼。由應用層產生，作為操作與稽核主鍵。';

COMMENT ON COLUMN withdrawals.request_id IS
'請求識別碼。這裡只做查詢與重送辨識的輔助欄位，不把它當成完整 idempotency 保證。';

COMMENT ON COLUMN withdrawals.account_id IS
'所屬帳戶。提款從哪個 account 出去，必須能直接查詢。';

COMMENT ON COLUMN withdrawals.asset_symbol IS
'所屬資產。必須與 account_assets 保持一致。';

COMMENT ON COLUMN withdrawals.chain_type IS
'鏈別。提款對應哪個網路，會影響地址格式與鏈上費用觀測。';

COMMENT ON COLUMN withdrawals.address IS
'收款地址。只保存外部地址字串，不保存任何密鑰或簽章材料。';

COMMENT ON COLUMN withdrawals.address_label IS
'收款地址備註。部分業務或鏈別會需要標記，但不應承載安全判斷。';

COMMENT ON COLUMN withdrawals.amount IS
'提現金額。使用 NUMERIC(38, 18) 避免浮點誤差。';

COMMENT ON COLUMN withdrawals.fee_amount IS
'手續費。這是展示與對帳欄位，不決定實際扣費策略。';

COMMENT ON COLUMN withdrawals.chain_transaction_id IS
'對應的鏈上交易。尚未廣播或尚未確認時可為 NULL。';

COMMENT ON COLUMN withdrawals.status IS
'提現狀態。這些值只代表流程階段，不代表資金已移出。';

COMMENT ON COLUMN withdrawals.created_at IS
'資料建立時間。由資料庫預設產生，供審計與對帳使用。';

COMMENT ON COLUMN withdrawals.updated_at IS
'資料最後更新時間。狀態進展、風控或對帳修正時由應用層維護。';
