-- P12-T08: Outbox, audit log, and idempotency schema.
-- 這份 migration 只建立高風險操作的去重、外部副作用與稽核資料結構。
-- 不實作 idempotency interceptor、event publisher、audit writer、ledger posting、deposit crediting 或 withdrawal runtime。
-- 這些表只提供 durable storage，實際重試、發佈與審計流程要由後續應用層與 runtime 實作。
-- Rollback 注意事項：若要回滾，先確認沒有後續流程依賴這些表；僅能刪除本 migration 建立的表，不得回寫既有資料。

-- Idempotency key 主檔。
-- 這不是完整的 runtime idempotency 保證，而是讓高風險操作能以 scope + key 做去重與對帳。
CREATE TABLE idempotency_keys (
    -- Idempotency key 唯一識別碼。由資料庫產生，作為查詢與稽核主鍵。
    idempotency_key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Idempotency 範圍。用來區分 ORDER_CREATE、WITHDRAWAL_REQUEST、LEDGER_POSTING、DEPOSIT_CONFIRMATION 等高風險操作。
    scope VARCHAR(32) NOT NULL,

    -- Idempotency key 值。與 scope 組合後才具有唯一意義。
    idempotency_key VARCHAR(128) NOT NULL,

    -- 請求識別碼。只用於追蹤與關聯，不可被誤解成單欄位完成完整 idempotency 保證。
    request_id VARCHAR(64),

    -- Idempotency 狀態。只描述處理流程狀態，不代表 runtime 已完成副作用。
    status VARCHAR(16) NOT NULL,

    -- 關聯的資源類型。用來記錄這筆去重鍵最後綁定到哪一類業務資源。
    resource_type VARCHAR(32),

    -- 關聯的資源識別碼。用來回查這筆去重鍵最終對應的業務物件。
    resource_id VARCHAR(128),

    -- 可選的 response code。只做查詢輔助，避免重送時需要重算整個流程。
    response_code INTEGER,

    -- 回應摘要。以文字形式保存，不在這裡定義 API schema，也不承擔 runtime response contract。
    response_summary TEXT,

    -- 到期時間。過期的 key 可重新清理，但清理策略仍由後續維運流程決定。
    expires_at TIMESTAMP WITH TIME ZONE,

    -- 資料建立時間。由資料庫預設產生，供審計與去重使用。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。狀態改變或 resource 綁定完成時由應用層維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_idempotency_keys_scope_key UNIQUE (scope, idempotency_key),
    CONSTRAINT ck_idempotency_keys_scope CHECK (scope IN ('ORDER_CREATE', 'ORDER_CANCEL', 'WITHDRAWAL_REQUEST', 'WITHDRAWAL_CANCEL', 'LEDGER_POSTING', 'DEPOSIT_CONFIRMATION', 'RESERVATION_HOLD', 'RESERVATION_RELEASE', 'ADMIN_ACTION')),
    CONSTRAINT ck_idempotency_keys_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'EXPIRED')),
    CONSTRAINT ck_idempotency_keys_response_code CHECK (response_code IS NULL OR response_code BETWEEN 100 AND 599)
);

CREATE INDEX idx_idempotency_keys_scope_status ON idempotency_keys (scope, status);
CREATE INDEX idx_idempotency_keys_request_id ON idempotency_keys (request_id);
CREATE INDEX idx_idempotency_keys_expires_at ON idempotency_keys (expires_at);
CREATE INDEX idx_idempotency_keys_resource_reference ON idempotency_keys (resource_type, resource_id);

COMMENT ON TABLE idempotency_keys IS
'Idempotency key 主檔。這不是完整的 runtime idempotency 保證，而是讓高風險操作能以 scope + key 做去重與對帳。';

COMMENT ON COLUMN idempotency_keys.idempotency_key_id IS
'Idempotency key 唯一識別碼。由資料庫產生，作為查詢與稽核主鍵。';

COMMENT ON COLUMN idempotency_keys.scope IS
'Idempotency 範圍。用來區分 ORDER_CREATE、WITHDRAWAL_REQUEST、LEDGER_POSTING、DEPOSIT_CONFIRMATION 等高風險操作。';

COMMENT ON COLUMN idempotency_keys.idempotency_key IS
'Idempotency key 值。與 scope 組合後才具有唯一意義。';

COMMENT ON COLUMN idempotency_keys.request_id IS
'請求識別碼。只用於追蹤與關聯，不可被誤解成單欄位完成完整 idempotency 保證。';

COMMENT ON COLUMN idempotency_keys.status IS
'Idempotency 狀態。只描述處理流程狀態，不代表 runtime 已完成副作用。';

COMMENT ON COLUMN idempotency_keys.resource_type IS
'關聯的資源類型。用來記錄這筆去重鍵最後綁定到哪一類業務資源。';

COMMENT ON COLUMN idempotency_keys.resource_id IS
'關聯的資源識別碼。用來回查這筆去重鍵最終對應的業務物件。';

COMMENT ON COLUMN idempotency_keys.response_code IS
'可選的 response code。只做查詢輔助，避免重送時需要重算整個流程。';

COMMENT ON COLUMN idempotency_keys.response_summary IS
'回應摘要。以文字形式保存，不在這裡定義 API schema，也不承擔 runtime response contract。';

COMMENT ON COLUMN idempotency_keys.expires_at IS
'到期時間。過期的 key 可重新清理，但清理策略仍由後續維運流程決定。';

COMMENT ON COLUMN idempotency_keys.created_at IS
'資料建立時間。由資料庫預設產生，供審計與去重使用。';

COMMENT ON COLUMN idempotency_keys.updated_at IS
'資料最後更新時間。狀態改變或 resource 綁定完成時由應用層維護。';

-- Outbox 事件主檔。
-- 這只保存 transactional outbox 所需的持久化事件，不會在 migration 內發送事件。
CREATE TABLE outbox_events (
    -- Outbox 事件識別碼。由資料庫產生，供排程與重試查詢使用。
    outbox_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 聚合類型。用來指向事件來源，例如 ORDER、WITHDRAWAL、DEPOSIT、RESERVATION、LEDGER_JOURNAL。
    aggregate_type VARCHAR(32) NOT NULL,

    -- 聚合識別碼。用來定位產生事件的業務物件。
    aggregate_id VARCHAR(128) NOT NULL,

    -- 事件類型。描述此次 outbox 事件的語意，例如 ORDER_CREATED 或 WITHDRAWAL_APPROVED。
    event_type VARCHAR(64) NOT NULL,

    -- 事件 payload。以文字保存序列化內容，避免 JSON 型別在 H2 / PostgreSQL 之間產生相容性問題。
    payload TEXT NOT NULL,

    -- 事件狀態。只描述 outbox 的配送流程，不代表已被外部系統消費。
    status VARCHAR(16) NOT NULL,

    -- 重試次數。用來支援失敗重送與 dead-letter 條件。
    retry_count INTEGER NOT NULL DEFAULT 0,

    -- 下次可用時間。讓 publisher 可以延後重送，而不是立刻 busy loop。
    available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 請求識別碼。只做來源關聯，不承諾完整去重。
    request_id VARCHAR(64),

    -- 成功發佈時間。只有在外部發佈完成後才應填值。
    published_at TIMESTAMP WITH TIME ZONE,

    -- 最近一次錯誤摘要。僅供排障，不能拿來當成外部契約。
    last_error TEXT,

    -- 資料建立時間。由資料庫預設產生，供重試與審計使用。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 資料最後更新時間。狀態變更、重試或發佈完成時由應用層維護。
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_outbox_events_status CHECK (status IN ('READY', 'PROCESSING', 'PUBLISHED', 'FAILED', 'DEAD_LETTER')),
    CONSTRAINT ck_outbox_events_retry_count CHECK (retry_count >= 0)
);

CREATE INDEX idx_outbox_events_status_available_at ON outbox_events (status, available_at);
CREATE INDEX idx_outbox_events_aggregate_reference ON outbox_events (aggregate_type, aggregate_id);
CREATE INDEX idx_outbox_events_event_type ON outbox_events (event_type);
CREATE INDEX idx_outbox_events_request_id ON outbox_events (request_id);
CREATE INDEX idx_outbox_events_created_at ON outbox_events (created_at);

COMMENT ON TABLE outbox_events IS
'Outbox 事件主檔。這只保存 transactional outbox 所需的持久化事件，不會在 migration 內發送事件。';

COMMENT ON COLUMN outbox_events.outbox_event_id IS
'Outbox 事件識別碼。由資料庫產生，供排程與重試查詢使用。';

COMMENT ON COLUMN outbox_events.aggregate_type IS
'聚合類型。用來指向事件來源，例如 ORDER、WITHDRAWAL、DEPOSIT、RESERVATION、LEDGER_JOURNAL。';

COMMENT ON COLUMN outbox_events.aggregate_id IS
'聚合識別碼。用來定位產生事件的業務物件。';

COMMENT ON COLUMN outbox_events.event_type IS
'事件類型。描述此次 outbox 事件的語意，例如 ORDER_CREATED 或 WITHDRAWAL_APPROVED。';

COMMENT ON COLUMN outbox_events.payload IS
'事件 payload。以文字保存序列化內容，避免 JSON 型別在 H2 / PostgreSQL 之間產生相容性問題。';

COMMENT ON COLUMN outbox_events.status IS
'事件狀態。只描述 outbox 的配送流程，不代表已被外部系統消費。';

COMMENT ON COLUMN outbox_events.retry_count IS
'重試次數。用來支援失敗重送與 dead-letter 條件。';

COMMENT ON COLUMN outbox_events.available_at IS
'下次可用時間。讓 publisher 可以延後重送，而不是立刻 busy loop。';

COMMENT ON COLUMN outbox_events.request_id IS
'請求識別碼。只做來源關聯，不承諾完整去重。';

COMMENT ON COLUMN outbox_events.published_at IS
'成功發佈時間。只有在外部發佈完成後才應填值。';

COMMENT ON COLUMN outbox_events.last_error IS
'最近一次錯誤摘要。僅供排障，不能拿來當成外部契約。';

COMMENT ON COLUMN outbox_events.created_at IS
'資料建立時間。由資料庫預設產生，供重試與審計使用。';

COMMENT ON COLUMN outbox_events.updated_at IS
'資料最後更新時間。狀態變更、重試或發佈完成時由應用層維護。';

-- 稽核紀錄主檔。
-- 這只保存高風險操作的可追溯紀錄，不包含任何 runtime writer 或 admin workflow。
CREATE TABLE audit_logs (
    -- 稽核紀錄識別碼。由資料庫產生，供查詢與對帳使用。
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- 行為者類型。描述誰觸發了這次高風險操作，例如 USER、ADMIN、SYSTEM、SERVICE。
    actor_type VARCHAR(16) NOT NULL,

    -- 行為者識別碼。用來定位實際操作者或服務主體。
    actor_id VARCHAR(64) NOT NULL,

    -- 動作類型。描述被審計的行為，例如 ORDER_CREATE、WITHDRAWAL_REQUEST、LEDGER_POSTING、ADMIN_ACTION。
    action_type VARCHAR(64) NOT NULL,

    -- 目標類型。描述被影響的資源類別，例如 ORDER、WITHDRAWAL、DEPOSIT、RESERVATION、LEDGER_JOURNAL。
    target_type VARCHAR(32) NOT NULL,

    -- 目標識別碼。描述被影響的具體資源。
    target_id VARCHAR(128) NOT NULL,

    -- 請求識別碼。用來串起原始請求與稽核紀錄，不代表完整 idempotency 保證。
    request_id VARCHAR(64) NOT NULL,

    -- 關聯識別碼。可用於跨 service 追蹤同一條鏈路。
    correlation_id VARCHAR(64),

    -- 操作結果。記錄這次高風險操作是成功、失敗還是被拒絕。
    outcome VARCHAR(16) NOT NULL,

    -- 原因說明。只有在需要人工回顧或失敗排障時才會填入。
    reason TEXT,

    -- 變更前狀態快照。以文字保存，供後續審計與事故分析。
    before_state TEXT,

    -- 變更後狀態快照。以文字保存，供後續審計與事故分析。
    after_state TEXT,

    -- 資料建立時間。這是稽核紀錄的時間錨點，之後不應更新。
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_audit_logs_actor_type CHECK (actor_type IN ('USER', 'ADMIN', 'SYSTEM', 'SERVICE')),
    CONSTRAINT ck_audit_logs_outcome CHECK (outcome IN ('SUCCESS', 'FAILURE', 'REJECTED'))
);

CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_type, actor_id);
CREATE INDEX idx_audit_logs_action_type ON audit_logs (action_type);
CREATE INDEX idx_audit_logs_target ON audit_logs (target_type, target_id);
CREATE INDEX idx_audit_logs_request_id ON audit_logs (request_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);

COMMENT ON TABLE audit_logs IS
'稽核紀錄主檔。這只保存高風險操作的可追溯紀錄，不包含任何 runtime writer 或 admin workflow。';

COMMENT ON COLUMN audit_logs.audit_log_id IS
'稽核紀錄識別碼。由資料庫產生，供查詢與對帳使用。';

COMMENT ON COLUMN audit_logs.actor_type IS
'行為者類型。描述誰觸發了這次高風險操作，例如 USER、ADMIN、SYSTEM、SERVICE。';

COMMENT ON COLUMN audit_logs.actor_id IS
'行為者識別碼。用來定位實際操作者或服務主體。';

COMMENT ON COLUMN audit_logs.action_type IS
'動作類型。描述被審計的行為，例如 ORDER_CREATE、WITHDRAWAL_REQUEST、LEDGER_POSTING、ADMIN_ACTION。';

COMMENT ON COLUMN audit_logs.target_type IS
'目標類型。描述被影響的資源類別，例如 ORDER、WITHDRAWAL、DEPOSIT、RESERVATION、LEDGER_JOURNAL。';

COMMENT ON COLUMN audit_logs.target_id IS
'目標識別碼。描述被影響的具體資源。';

COMMENT ON COLUMN audit_logs.request_id IS
'請求識別碼。用來串起原始請求與稽核紀錄，不代表完整 idempotency 保證。';

COMMENT ON COLUMN audit_logs.correlation_id IS
'關聯識別碼。可用於跨 service 追蹤同一條鏈路。';

COMMENT ON COLUMN audit_logs.outcome IS
'操作結果。記錄這次高風險操作是成功、失敗還是被拒絕。';

COMMENT ON COLUMN audit_logs.reason IS
'原因說明。只有在需要人工回顧或失敗排障時才會填入。';

COMMENT ON COLUMN audit_logs.before_state IS
'變更前狀態快照。以文字保存，供後續審計與事故分析。';

COMMENT ON COLUMN audit_logs.after_state IS
'變更後狀態快照。以文字保存，供後續審計與事故分析。';

COMMENT ON COLUMN audit_logs.created_at IS
'資料建立時間。這是稽核紀錄的時間錨點，之後不應更新。';
