export const adminNavItems = [
  { to: '/admin', labelKey: 'nav.admin.dashboard' },
  { to: '/admin/users', labelKey: 'nav.admin.users' },
  { to: '/admin/assets', labelKey: 'nav.admin.assets' },
  { to: '/admin/wallet', labelKey: 'nav.admin.wallet' },
  { to: '/admin/spot', labelKey: 'nav.admin.spot' },
  { to: '/admin/futures', labelKey: 'nav.admin.futures' },
  { to: '/admin/margin', labelKey: 'nav.admin.margin' },
  { to: '/admin/risk', labelKey: 'nav.admin.risk' },
  { to: '/admin/market-makers', labelKey: 'nav.admin.marketMakers' },
  { to: '/admin/insurance-fund', labelKey: 'nav.admin.insuranceFund' },
  { to: '/admin/reconciliation', labelKey: 'nav.admin.reconciliation' },
  { to: '/admin/operation-logs', labelKey: 'nav.admin.operationLogs' },
  { to: '/admin/settings', labelKey: 'nav.admin.settings' },
] as const;
