package com.lumix.marketdata.book;

/**
 * 固定 projection 原因碼，供未來指標與 resync evidence 使用。
 */
public enum OrderBookProjectionReason {
    SNAPSHOT_BASELINE_ACCEPTED,
    CONTIGUOUS_DELTA_APPLIED,
    DUPLICATE_ADMISSION,
    ADMISSION_NOT_ACCEPTED,
    ADMISSION_EVENT_MISMATCH,
    NON_BOOK_EVENT,
    NON_BOOK_STREAM,
    STREAM_KEY_MISMATCH,
    SNAPSHOT_REQUIRED,
    DELTA_SEQUENCE_NOT_CONTINUOUS,
    ADMISSION_CURSOR_BASELINE_MISMATCH,
    PROJECTION_IDENTITY_ALREADY_APPLIED,
    LEVEL_LIMIT_EXCEEDED,
    CROSSED_BOOK_REJECTED,
    QUANTITY_OVERFLOW
}
