-- 檔案用途：SQL migration，建立成交流水 read model。
CREATE TABLE IF NOT EXISTS turnover_records (
    id CHAR(36) PRIMARY KEY,
    schema_version INT NOT NULL,
    uid BIGINT NOT NULL,
    account_id VARCHAR(64) NULL,
    symbol VARCHAR(32) NOT NULL,
    strategy_id VARCHAR(128) NULL,
    market_maker_id VARCHAR(128) NULL,
    order_id CHAR(36) NOT NULL,
    match_id VARCHAR(128) NULL,
    trade_seq BIGINT NOT NULL,
    quantity DECIMAL(38, 18) NOT NULL,
    price DECIMAL(38, 18) NOT NULL,
    notional DECIMAL(38, 18) NOT NULL,
    traded_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    UNIQUE KEY uk_turnover_trade_order (trade_seq, order_id),
    KEY idx_turnover_uid_created (uid, created_at),
    KEY idx_turnover_symbol_created (symbol, created_at),
    KEY idx_turnover_strategy (uid, strategy_id, created_at),
    KEY idx_turnover_market_maker (market_maker_id, created_at),
    KEY idx_turnover_match (match_id),
    CONSTRAINT chk_turnover_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT chk_turnover_price_non_negative CHECK (price >= 0),
    CONSTRAINT chk_turnover_notional_non_negative CHECK (notional >= 0)
);
